indigooj/OJ/urls.py
from django.conf.urls import url

from . import views

app_name = "OJ"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^problem/$', views.problemset, name='problemset'),
    url(r'^problem/(?P<id>[0-9]+)/$', views.problem, name='problem'),
    url(r'^problem/(?P<id>[0-9]+)/(?P<contest>[0-9]+)/$', views.problem, name='contestproblem'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^status/$', views.statuslist, name='statuslist'),
    url(r'^status/(?P<id>[0-9]+)/$', views.status, name='status'),
    url(r'^status/user/', views.userProblemStatus, name='userstatus'),
    url(r'^contest/$', views.contestList, name="contestlist"),
    url(r'^contest/sign/$',
        views.contestSign, name="contestsign"),
    url(r'^contest/(?P<id>[0-9]+)/$', views.contest, name="contest")
]

indigooj/indigooj/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('OJ.urls'))
]

indigooj/OJ/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    accountname = models.CharField(max_length=20)
    email = models.EmailField(blank=True)
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    accepted = models.PositiveIntegerField(default=0)
    submitted = models.PositiveIntegerField(default=0)

    def __unicode__(self):  # __str__ in py3
        return self.accountname


class OnlineOJ(models.Model):
    name = models.CharField(max_length=50)
    link = models.URLField()

    def __unicode__(self):
        return self.name


class Problem(models.Model):
    oj = models.ForeignKey(OnlineOJ, on_delete=models.CASCADE)
    id = models.PositiveIntegerField(primary_key=True)
    number = models.PositiveIntegerField()
    submitted = models.PositiveIntegerField(default=0)
    accepted = models.PositiveIntegerField(default=0)
    submitted_on_oringin = models.PositiveIntegerField(default=0)
    accepted_on_oringin = models.PositiveIntegerField(default=0)
    title = models.CharField(max_length=50)
    time_limit = models.CharField(max_length=20, blank=True)
    mem_limit = models.CharField(max_length=20, blank=True)
    detail = models.CharField(max_length=2000)
    sample = models.CharField(max_length=1000, blank=True)
    sampleinput = models.CharField(max_length=500, default='')
    sampleoutput = models.CharField(max_length=500, default='')
    source = models.CharField(max_length=200, default='')

    def __unicode__(self):
        return str(self.id)


class Status(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    subtime = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=100)
    time = models.PositiveIntegerField(default=0)
    mem = models.PositiveIntegerField(default=0)
    lan = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    codelength = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return str(id) + ':' + self.problem.title


class Contest(models.Model):
    title = models.CharField(max_length=200)
    assignlimit = models.DateTimeField()
    starttime = models.DateTimeField()
    endtime = models.DateTimeField()
    candidates = models.ManyToManyField(User, through="ContestLog",
                                        through_fields=(
                                            "contest", "candidate"),
                                        )

    def __unicode__(self):
        return self.title


class ContestProblem(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    point = models.IntegerField()
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.contest.title + self.problem.title


class ContestProblemStatus(models.Model):
    problem = models.ForeignKey(ContestProblem, on_delete=models.CASCADE)
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(default=0)
    laststatus = models.CharField(max_length=100, default="Unsubmitted")
    starttime = models.DateTimeField(auto_now_add=True)
    endtime = models.DateTimeField(blank=True)

    def __unicode__(self):
        return self.problem.problem.title + str(self.status)


class ContestLog(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    point = models.IntegerField(default=0)
    problemsolved = models.ManyToManyField(ContestProblem, blank=True)

    def __unicode__(self):
        return self.contest.title + self.candidate.accountname

indigooj/OJ/views.py
from django.shortcuts import render
from django.http import HttpResponse
from User import UserAction
from Problem import ProblemView, StatusView
from Contest import ContestView

# Create your views here.


def index(request):  # index may be beautiful
    try:
        uid = request.session['uid']
        account = request.session['accountname']
    except KeyError:
        uid = ''
        account = ''

    return render(request, 'OJ/index.html', {'uid': uid, 'account': account})


def login(request):
    return UserAction.login(request)


def logout(request):
    return UserAction.logout(request)
    # return HttpResponse("<h1>Logout</h1>" + request.META['HTTP_REFERER'])


def register(request):
    return UserAction.register(request)


def problemset(request):
    return ProblemView.problemset(request)


def problem(request, id ,contest=0):
    return ProblemView.problem(request, id,contest)


def statuslist(request):
    return StatusView.statuslist(request)


def status(request, id):
    return StatusView.status(request, id)


def userProblemStatus(request):
    return StatusView.userProblemStatus(request)


def contestList(request):
    return ContestView.contestlist(request)


def contestSign(request):
    return ContestView.contestsign(request)


def contest(request, id):
    return ContestView.contest(request, id)

indigooj/OJ/templates/OJ/contest.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>Contest</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

        <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <link href="{% static "OJ/mainstyle.css" %}" rel="stylesheet">

        <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>

        <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
<body>

{% include "OJ/navbar.html" %}

<!--<header id="index-header" style="margin-top: 50px;">
    <div class="container">
        <div class="intro">
            <p class="fadeInUp animated">欢迎来到IndigoOJ</p>
            <p class="welcome fadeInUp animated">靛蓝的深沉</p>
            {% if uid != '' %}
            <a href="{% url 'OJ:problemset'%}" type="button" class="btn btn-default btn-lg">遁去做题</a>
            {% else %}
            <a href = "{% url 'OJ:register' %}" type="button"  class="btn btn-default btn-lg">加入我们</a>
            {% endif %}
            
        </div>
    </div>
</header>-->

<div class="container" style="margin-top: 50px;font-family:'微软雅黑';">
    <h2 class="page-header">{{ contest.title }}</h2>
    <div class="container">
        {% include contest.template %}
    </div>
    <div class="row">
    <h3 class="page-header col-md-12">题目列表</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>题目</th>
                <th>分值</th>
            </tr>
        </thead>
        <tbody>
            {% for i in problems %}
            <tr>
                <td><a href="{% url 'OJ:contestproblem' i.problem.id pk %}">{{i.problem.title}}</a></td>
                <td>{{i.point}}</td>
            </tr>
            {% endfor %}
            
        </tbody>
    </table>
    {% if attend == True %}
        <h3 class="page-header col-md-12">我解决的问题</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>题目</th>
                <th>分值</th>
            </tr>
        </thead>
        <tbody>
            {% for i in contestlog.problemsolved.all %}
            <tr>
                <td><a href="{% url 'OJ:contestproblem' i.problem.id pk %}">{{i.problem.title}}</a></td>
                <td>{{i.point}}</td>
            </tr>
            {% endfor %}
            
        </tbody>
    </table>
    {% endif %}
    <h3 class="page-header col-md-12">得分表</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>选手</th>
                <th>分值</th>
                <th>解决问题数</th>
            </tr>
        </thead>
        <tbody>
            {% for i in contestrank %}
            <tr>
                <td>{{i.account}}</td>
                <td>{{i.point}}</td>
                <td>{{i.problemsolved.count}}</td>
            </tr>
            {% endfor %}
            
        </tbody>
    </table>
    </div>
</div>

</body>
</html>

indigooj/OJ/templates/OJ/contestlist.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>Contest - IndigoOJ</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

        <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <link href="{% static "OJ/mainstyle.css" %}" rel="stylesheet">

        <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>

        <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
<body role="document">

{% include "OJ/navbar.html" %}

<header id="contest-header" style="margin-top: 50px;">
    <div class="container">
        <div class="contest-intro center-block">
            <p class="fadeIn animated">Contest</p>
            <p class="welcome fadeIn animated">在这里磨练诸多技术</p>
        </div>
    </div>
</header>


<div class="container" style="font-family: '微软雅黑';" >
    <div class="row">
    <h2 class="page-header col-md-12">在线竞赛</h2>
        <div class="alert alert-info col-md-6">
        <strong>注意</strong> 
        <p>请阅读相关说明</p>
    </div>
    </div>
    <div class="row">
        <h3>竞赛须知：</h3>
        <ul >
            <li class="">
            <p>
                参加比赛之前需要<b>报名(Assign)</b>，报名之后方可参加竞赛。
            </p>
            </li>
            <li class="">
            <p>
                报名在竞赛之前且有<b>截止时间</b>，以服务器时间为准。
            </p>
            </li>
            <li class="">
            <p>
                在竞赛开放之后，进入相应的竞赛页面参与竞赛，仅接受Accept得分，其余结果不得分，每题有不同分值，<b>得分最多并且总用时最少者</b>获得胜利。
            </p>
            </li>
            <li class="">
            <p>
                竞赛题目从OJ中抽选，只有<b>从此页入口进入做题有效</b>，实时得分排名在竞赛页面查看
            </p>
            </li>
        </ul>
        
    </div>
    <div class="row">
        <h2 class="page-header col-md-12">竞赛列表</h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>AssignLimit</th>
                    <th>StartTime</th>
                    <th>EndTime</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
                {% for i in contestlist %}
                    <tr>
                    <td>{{ i.title }}</td>
                    <td>{{ i.assignlimit|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ i.starttime|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ i.endtime|date:"Y-m-d H:i:s" }}</td>
                    <td><a  class="info">
                        {% if i.status == "unopen" %}
                            <button contest="{{i.pk}}" type="button" class="btn btn-default sign">报名</button>
                        {% elif i.status == "signed" %}
                            <span class="success">Signed</span>
                        {% elif i.status == "pending" %}
                            span class="info">Pending</span>
                        {% elif i.status == "contesting" %}
                            <a href="{% url 'OJ:contest' i.pk %}">EnterContest</a>
                        {% elif i.status == "unsigned" %}
                            <span class="info">WatchContest</span>
                        {% else %}
                            <a href="{% url 'OJ:contest' i.pk %}" class="info">Inspect</a>
                            <!--<a contest="{{i.pk}}" class="sign" href="{# {% url 'OJ:contestsign' i.pk %} #}">?</a>-->
                        {% endif %}
                    </a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

</body>
<script>
    $(document).ready(function() {
        $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
    })
    });

    $(document).ready(function(){
        $(".sign").click(function(){
            var pk = $(this).attr('contest');
            $.ajax({
                url: '{% url "OJ:contestsign" %}',
                type: 'POST',
                dataType: 'html',
                data: {pk: pk},
            })
            .done(function(result) {
                alert(result);
            })
            .fail(function() {
                alert("报名失败");
            });
            $(this).attr("disabled","true")
        })
    });
</script>
</html>

indigooj/OJ/templates/OJ/index.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>IndigoOJ</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

        <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <link href="{% static "OJ/mainstyle.css" %}" rel="stylesheet">

        <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>

        <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
<body role="document">
<!-- <nav class="navbar alert">
<div class="container">
    <div class="row clearfix head">
        <div class="col-md-12 column">
        <a href = "{% url 'OJ:problemset' %}">Problems</a>

<a href = "{% url 'OJ:statuslist' %}">Status</a>

{% if uid != '' %}
    <h1>Welcome {{account}} !</h1>
    <a href = "{% url 'OJ:logout' %}">注销</a>
{% else %}
    <span class="glyphicon glyphicon-user"></span>
    <a href = "{% url 'OJ:login' %}">登陆</a>
<a href = "{% url 'OJ:register' %}">注册</a>
{% endif %}
        </div>
    </div>
</div>
</nav> -->
{% include "OJ/navbar.html" %}
<header id="index-header" style="margin-top: 50px;">
    <div class="container">
        <div class="intro">
            <p class="fadeInUp animated">欢迎来到IndigoOJ</p>
            <p class="welcome fadeInUp animated">靛蓝的深沉</p>
            {% if uid != '' %}
            <a href="{% url 'OJ:problemset'%}" type="button" class="btn btn-default btn-lg">遁去做题</a>
            {% else %}
            <a href = "{% url 'OJ:register' %}" type="button"  class="btn btn-default btn-lg">加入我们</a>
            {% endif %}
            
        </div>
    </div>
</header>
<div class="container" >
    
</div>
{% include "OJ/bottom.html" %}
</body>
</html>

indigooj/OJ/templates/OJ/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>IndigoOJ</title>

        <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>

        <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
<body>
{% include "OJ/navbar.html" %}
<div class="container" style="padding-top:100px">
    <form role="form" action="{% url 'OJ:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="" class="control-label">用户名</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="" class="control-label">密码</label>
            {{ form.password }}
        </div>

        {# {{ form.as_table }} #}


    <button type="submit" class="btn btn-primary">
    Submit</button>
</form>
</div>
</body>
</html>

indigooj/OJ/templates/OJ/navbar.html
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Menu</span>
        <span class="glyphicon glyphicon-th-list"></span>
    </button>
    <a class="navbar-brand" href="{% url 'OJ:index' %}">IndigoOJ</a>

</div>
<div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>
            <a href="{% url 'OJ:index' %}">主页</a>
        </li>
        <li>
            <a href="{% url 'OJ:problemset'%}">Problems</a>
        </li>
        <li>
            <a href="{% url 'OJ:statuslist'%}">Status</a>
        </li>
        <li>
            <a href="{% url 'OJ:contestlist'%}">Contest</a>
        </li>
        <li>
            <a href="{% url 'OJ:userstatus'%}">MyStatus</a>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if uid != '' %}
    <li>
    <a >Welcome {{account}} !</a>
    </li>
    <li>
    <a href = "{% url 'OJ:logout' %}"><span class="glyphicon glyphicon-log-out"></span> 注销</a>
    </li>
    {% else %}
    <li>
    <a href = "{% url 'OJ:login' %}"><span class="glyphicon glyphicon-log-in"></span> 登录</a>
    </li>
    <li>
        <a href = "{% url 'OJ:register' %}"><span class="glyphicon glyphicon-user"></span> 注册</a>
    </li>
        {% endif %}
    </ul>
</div>
</div>   
</nav>

indigooj/OJ/templates/OJ/problem.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ problem.title }} - IndigoOJ</title>

        <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js" ></script>

        <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="text/javascript">

</script>

    </head>
<body>
{% include "OJ/navbar.html" %}

<div class="container" style="padding-top:50px;">

 <div class="page-header">   <h3>{{ problem.title }}</h3>
 </div>
<p>Time Limit:<span class="text-info">{{ problem.time_limit }}</span> <br> Memory Limit:{{ problem.mem_limit }} <br> Soucre:{{problem.source}}<br>
Accepted:<span class="text-info">{{ problem.accepted }}</span> <br>Submitted:<span class="text-info">{{ problem.submitted }}</span> </p>
<div class="page-header"><h4>Detail</h4></div>
<div class="container">{{ problem.detail }}</div>
<div class="page-header"><h4>Sampleinput</h4></div>
<div class="container">
    {% autoescape off %}
<pre class="col-md-8">{{ problem.sampleinput}}</pre>
    {% endautoescape %}
</div>

<div class="page-header"><h4>Sampleoutput</h4></div>
<div class="container">
    {% autoescape off %}
<pre class="col-md-8">{{ problem.sampleoutput}}</pre>
    {% endautoescape %}
</div>


<hr>

<form id="codeform" action="{% url 'OJ:problem' problem.id %}" method="post">
    <table>
        {% csrf_token %}
        
        {{ form }}
        
    </table>
    <div class="row col-md-10" style="min-height:400px;border-color:GRAY;border-width:10px;border-radius: 4px 4px 0 0;">
        <div class="" id="editor" style="min-height:400px;border-color:GRAY;border-width:10px;border-radius: 4px 4px 0 0;"></div>
    </div>
    <div class="row col-md-10" style="">
        <button id="submit" class="btn btn-primary pull-right" style="margin-top:20px" type="submit" >提交</button>
    </div>
</form>

<h3 id="test"></h3>
</div>

</body>


<!--<script>
        $("#code").attr("hidden","true");
</script>-->

<script type="text/javascript">
    var editor=ace.edit("editor");
    editor.setTheme("ace/theme/textmate");
    editor.getSession().setMode("ace/mode/c_cpp");
    editor.setAutoScrollEditorIntoView(true);
    editor.setShowPrintMargin(false);
    editor.setFontSize(15);
    $(document).ready(function(){
        $("#codeform").submit(function() {
            $("#code").html(editor.getValue());
        });
        /*$("#submit").click(function(){
            $("#code").html(editor.getValue());
        })*/
    })
</script>
<script type="text/javascript">
    
</script>


</html>

indigooj/OJ/templates/OJ/problemset.html
<!DOCTYPE html>
<html>
    <head>
        <title>Problems - IndigoOJ</title>

        <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>

        <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
<body>
{% include "OJ/navbar.html" %}

<div class="container" style="padding:50px;">

<div class="row">
<h1 class="page-header col-md-12">ProblemSet</h1>
	<table class="table table-striped">
	<thead>
		<tr>
			<th class="col-md-1">ID</th>
			<th class="col-md-1">Title</th>
			<th class="col-md-1">Number</th>
			<th class="col-md-2">ACRate</th>
			<th class="col-md-2">ACRate(origin)</th>
		</tr>
	</thead>
	<tbody>
		{% for problem in problem_list %}
		<tr>
			<td>{{ problem.id }}</td>
			<td><a href = "{% url 'OJ:problem' problem.id %}">{{ problem.title }}</a></td>
			<td>{{ problem.number }}</td>
			<td><div class="progress"><div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{ problem.ratio }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ problem.ratio }}%;"><span style="z-index:5;color:BLACK;">{{ problem.ratio }}%</span>
			</div></div>
			<td><div class="progress"><div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{ problem.ratio }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ problem.ratio_on_oringin }}%;"><span style="z-index:5;color:BLACK;">{{ problem.ratio_on_oringin }}%</span></div></div></td>
		</tr>
		<!-- %({{ problem.accepted_on_oringin }} / {{ problem.submitted_on_oringin }})  %({{ problem.accepted }} / {{ problem.submitted }}) -->
		{% endfor %}
	</tbody>
</table>
</div>
<div class="row" style="text-align:center">
<ul class="pagination">

	<li><a href="{% url 'OJ:problemset'%}">&laquo;</a></li>
	<li><a href="#">‹</a></li>
<!--	<li><a href="{% url 'OJ:problemset' %}?page={{ page|add:1 }}">{{ page|add:1  }}</a></li>
	<li><a href="{% url 'OJ:problemset' %}">{{ page|add:2  }}</a></li>
	<li><a href="{% url 'OJ:problemset'%}">{{ page|add:3  }}</a></li>
	<li><a href="{% url 'OJ:problemset'%}">{{ page|add:4  }}</a></li>
	<li><a href="{% url 'OJ:problemset'%}">{{ page|add:5  }}</a></li>
	<li><a href="{% url 'OJ:problemset'%}">{{ page|add:6  }}</a></li>
	<li><a href="{% url 'OJ:problemset'%}">{{ page|add:7  }}</a></li>
	<li><a href="{% url 'OJ:problemset'%}">{{ page|add:8  }}</a></li>
	<li><a href="{% url 'OJ:problemset'%}">{{ page|add:9  }}</a></li>
	-->

	<li {% if page == pagelist.1 %}class="active"{% endif %} ><a href="{% url 'OJ:problemset' %}?page={{ pagelist.1 }}">{{ pagelist.1  }}</a></li>
	<li {% if page == pagelist.2 %}class="active"{% endif %}><a href="{% url 'OJ:problemset' %}?page={{ pagelist.2 }}">{{ pagelist.2  }}</a></li>
	<li {% if page == pagelist.3 %}class="active"{% endif %}><a href="{% url 'OJ:problemset' %}?page={{ pagelist.3 }}">{{ pagelist.3  }}</a></li>
	<li {% if page == pagelist.4 %}class="active"{% endif %}><a href="{% url 'OJ:problemset' %}?page={{ pagelist.4 }}">{{ pagelist.4  }}</a></li>
	<li {% if page == pagelist.5 %}class="active"{% endif %}><a href="{% url 'OJ:problemset' %}?page={{ pagelist.5 }}">{{ pagelist.5  }}</a></li>
	<li {% if page == pagelist.6 %}class="active"{% endif %}><a href="{% url 'OJ:problemset' %}?page={{ pagelist.6 }}">{{ pagelist.6  }}</a></li>
	<li {% if page == pagelist.7 %}class="active"{% endif %}><a href="{% url 'OJ:problemset' %}?page={{ pagelist.7 }}">{{ pagelist.7  }}</a></li>
	<li {% if pagelist.8 == '0' %}class="disabled"{%else%}{% if page == pagelist.7 %}class="active"{% endif %}{% endif %}><a href={% if pagelist.8 == '0' %}"#"{%else%}"{% url 'OJ:problemset' %}?page={{ pagelist.8 }}"{% endif %}>{% if pagelist.8 == '0' %}...{%else%}{{ pagelist.8  }}{% endif %}</a></li>
	<li {% if page == pagelist.9 %}class="active"{% endif %}><a href="{% url 'OJ:problemset' %}?page={{ pagelist.9 }}">{{ pagelist.9  }}</a></li>
	<li><a href="{% url 'OJ:problemset'%}">›</a></li>
	<li><a href="{% url 'OJ:problemset'%}?page={{ lastpage }}">&raquo;</a></li> 
</ul>

</div>
</div>



</body>


</html>